version: '3.8'

services:
  postgres:
    image: 'postgres:14-alpine3.14'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
      - PGDATA=/var/lib/postgresql/data/db
    ports:
      - 5432:5432